import type { Metadata } from "next";
import { Bellefair, Barlow_Condensed, Barlow} from "next/font/google";
import { createContext } from "react";

import "swiper/css";
import "./globals.css";
import "./CSSModules/backgroundMediaQuery.css"
import WebContent from "../data.json"


export const metadata: Metadata = {
  title: "Space Tourism",
  description: "Generated by create next app",
}


const bellefair = Bellefair({
  subsets: ['latin'],
  weight: '400',
  variable: "--font-bellefair"
})

const barlowCondensed = Barlow_Condensed({
  subsets: ['latin'],
  weight: ['200', '400', '700'],
  variable: "--font-barlow-condensed"
})

const barlow = Barlow({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-barlow'
})




export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
   
      <html lang="en">
        <body className={`${bellefair.variable} ${barlowCondensed.variable} ${barlow.variable}`}>
          <main className="bg-dark-blue">
            {children}
          </main>
          <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-element-bundle.min.js"></script>
        </body>
      </html>

    
  );
}
