import type { Metadata } from "next";
import { Bellefair, Barlow_Condensed, Barlow} from "next/font/google";
import "./globals.css";
import "./CSSModules/hompage.css"
import "./CSSModules/destination.css"



const bellefair = Bellefair({
  subsets: ['latin'],
  weight: '400',
  variable: "--bellefair"
})

const barlowCondensed = Barlow_Condensed({
  subsets: ['latin'],
  weight: ['200', '400', '700'],
  variable: "--barlow-condensed"
})

const barlow = Barlow({
  subsets: ['latin'],
  weight: '400',
  variable: '--barlow'
})


export const metadata: Metadata = {
  title: "Space Tourism",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={`${bellefair.variable} ${barlowCondensed.variable} ${barlow.variable}`}>
        {children}
        <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-element-bundle.min.js"></script>
      </body>
    </html>
  );
}
